// <auto-generated />
using AsyncInn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AsyncInn.Migrations
{
    [DbContext(typeof(AsyncInnDbContext))]
    [Migration("20191104183138_seededData")]
    partial class seededData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AsyncInn.Models.Amenities", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Coffee Maker"
                        },
                        new
                        {
                            ID = 3,
                            Name = "California King Bed"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Full Kitchen"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Game System"
                        });
                });

            modelBuilder.Entity("AsyncInn.Models.Hotel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "Seattle",
                            Name = "Nier Waterfront",
                            Phone = "(206)994-1524",
                            State = "Washington",
                            StreetAddress = "2BA2 Replicant Rd, Seattle, WA"
                        },
                        new
                        {
                            ID = 2,
                            City = "Bellevue",
                            Name = "Hotel of Light",
                            Phone = "(206)485-6491",
                            State = "Washington",
                            StreetAddress = "8000 Ascian Rd, Bellevue, WA"
                        },
                        new
                        {
                            ID = 3,
                            City = "Seattle",
                            Name = "Mythra Respite Inn",
                            Phone = "(425)641-3001",
                            State = "Washington",
                            StreetAddress = "6565 Rex Rd, Bellingham, WA"
                        },
                        new
                        {
                            ID = 4,
                            City = "Seattle",
                            Name = "Divinity's Rest",
                            Phone = "(206)569-9515",
                            State = "Washington",
                            StreetAddress = "301 Larian Ln, Seattle, WA"
                        },
                        new
                        {
                            ID = 5,
                            City = "Portland",
                            Name = "Lion's Pride Inn",
                            Phone = "(503)132-1323",
                            State = "Oregon",
                            StreetAddress = "2004 Nortshire Blvd, Portland, OR"
                        });
                });

            modelBuilder.Entity("AsyncInn.Models.HotelRoom", b =>
                {
                    b.Property<int>("HotelID")
                        .HasColumnType("int");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<bool>("PetFriendly")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.HasKey("HotelID", "RoomNumber");

                    b.ToTable("HotelRooms");
                });

            modelBuilder.Entity("AsyncInn.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Layout")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Layout = 0,
                            Name = "Yonah Yawn"
                        },
                        new
                        {
                            ID = 2,
                            Layout = 2,
                            Name = "Eorzean Escape"
                        },
                        new
                        {
                            ID = 3,
                            Layout = 0,
                            Name = "Nya Nap"
                        },
                        new
                        {
                            ID = 4,
                            Layout = 2,
                            Name = "The Red Prince"
                        },
                        new
                        {
                            ID = 5,
                            Layout = 1,
                            Name = "Moon Glade"
                        },
                        new
                        {
                            ID = 6,
                            Layout = 1,
                            Name = "Good Sleep In Here"
                        });
                });

            modelBuilder.Entity("AsyncInn.Models.RoomAmenities", b =>
                {
                    b.Property<int>("AmenitiesID")
                        .HasColumnType("int");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.HasKey("AmenitiesID", "RoomID");

                    b.ToTable("RoomAmenities");
                });
#pragma warning restore 612, 618
        }
    }
}
